camera:
  ros__parameters:
    serial_no: 727212071015 # d435
    align_depth: false
    enable_pointcloud: false
    #base_frame_id:
    color0:
      enabled: true
      resolution: [640,480]
      fps: 30
    depth0:
      enabled: true
      resolution: [640,480]
      fps: 30
    infra1:
      enabled: true
      resolution: [640,480]
      fps: 30
    infra2:
      enabled: true
      resolution: [640,480]
      fps: 30